const BUSINESS_COLUMN_DATA = [
  {
    id: 'organization-hierarchy',
    field: 'organizationHierarchy',
    label: '组织',
    width: 216,
    dataType: 'string',
    editable: false,
    searchable: true,
    frozen: true,
  },
  {
    id: 'subject-hierarchy',
    field: 'subjectHierarchy',
    label: '科目',
    width: 194,
    dataType: 'string',
    editable: false,
    searchable: true,
    frozen: true,
  },
  {
    id: 'functional-attribute',
    field: 'functionalAttribute',
    label: '功能属性',
    width: 154,
    dataType: 'string',
    editor: {
      type: 'text',
    },
    editable: true,
    searchable: true,
    frozen: true,
  },
  {
    id: 'budget-2025',
    field: 'budget2025',
    label: '2025年',
    children: [
      {
        id: 'annual-total',
        field: 'annualTotal',
        label: '全年合计',
        width: 114,
        dataType: 'number',
        format: 'decimal',
        editor: {
          type: 'number',
        },
        editable: true,
      },
      {
        id: 'january',
        field: 'january',
        label: '1月',
        width: 92,
        dataType: 'number',
        format: 'decimal',
        editor: {
          type: 'number',
        },
        editable: true,
      },
      {
        id: 'february',
        field: 'february',
        label: '2月',
        width: 92,
        dataType: 'number',
        format: 'decimal',
        editor: {
          type: 'number',
        },
        editable: true,
      },
      {
        id: 'march',
        field: 'march',
        label: '3月',
        width: 92,
        dataType: 'number',
        format: 'decimal',
        editor: {
          type: 'number',
        },
        editable: true,
      },
      {
        id: 'april',
        field: 'april',
        label: '4月',
        width: 92,
        dataType: 'number',
        format: 'decimal',
        editor: {
          type: 'number',
        },
        editable: true,
      },
      {
        id: 'may',
        field: 'may',
        label: '5月',
        width: 92,
        dataType: 'number',
        format: 'decimal',
        editor: {
          type: 'number',
        },
        editable: true,
      },
      {
        id: 'june',
        field: 'june',
        label: '6月',
        width: 92,
        dataType: 'number',
        format: 'decimal',
        editor: {
          type: 'number',
        },
        editable: true,
      },
      {
        id: 'july',
        field: 'july',
        label: '7月',
        width: 92,
        dataType: 'number',
        format: 'decimal',
        editor: {
          type: 'number',
        },
        editable: true,
      },
      {
        id: 'august',
        field: 'august',
        label: '8月',
        width: 92,
        dataType: 'number',
        format: 'decimal',
        editor: {
          type: 'number',
        },
        editable: true,
      },
      {
        id: 'september',
        field: 'september',
        label: '9月',
        width: 92,
        dataType: 'number',
        format: 'decimal',
        editor: {
          type: 'number',
        },
        editable: true,
      },
      {
        id: 'october',
        field: 'october',
        label: '10月',
        width: 92,
        dataType: 'number',
        format: 'decimal',
        editor: {
          type: 'number',
        },
        editable: true,
      },
      {
        id: 'november',
        field: 'november',
        label: '11月',
        width: 92,
        dataType: 'number',
        format: 'decimal',
        editor: {
          type: 'number',
        },
        editable: true,
      },
      {
        id: 'december',
        field: 'december',
        label: '12月',
        width: 92,
        dataType: 'number',
        format: 'decimal',
        editor: {
          type: 'number',
        },
        editable: true,
      },
    ],
  },
];

const BUSINESS_DATA = [
  {
    id: 'cr-micro-group',
    name: '华润微电子集团',
    hierarchyRole: 'group',
    functionalAttribute: '-',
    annualTotal: 43200,
    january: 3600,
    february: 3600,
    march: 3600,
    april: 3600,
    may: 3600,
    june: 3600,
    july: 3600,
    august: 3600,
    september: 3600,
    october: 3600,
    november: 3600,
    december: 3600,
    children: [
      {
        id: 'headquarters',
        name: '华润微电子本部',
        hierarchyRole: 'businessUnit',
        functionalAttribute: '-',
        annualTotal: 7200,
        january: 600,
        february: 600,
        march: 600,
        april: 600,
        may: 600,
        june: 600,
        july: 600,
        august: 600,
        september: 600,
        october: 600,
        november: 600,
        december: 600,
        regionSummaries: [
          {
            id: 'headquarters-expense-summary',
            name: '费用汇总',
            hierarchyRole: 'subjectSummary',
            functionalAttribute: '-',
            annualTotal: 7200,
            january: 600,
            february: 600,
            march: 600,
            april: 600,
            may: 600,
            june: 600,
            july: 600,
            august: 600,
            september: 600,
            october: 600,
            november: 600,
            december: 600,
            children: [
              {
                id: 'headquarters-subtotal',
                name: '日常费用合计',
                hierarchyRole: 'subjectDetail',
                functionalAttribute: '-',
                annualTotal: 7200,
                january: 600,
                february: 600,
                march: 600,
                april: 600,
                may: 600,
                june: 600,
                july: 600,
                august: 600,
                september: 600,
                october: 600,
                november: 600,
                december: 600,
              },
              {
                id: 'headquarters-office',
                name: '费用-办公费',
                hierarchyRole: 'subjectDetail',
                functionalAttribute: '管理',
                annualTotal: 1200,
                january: 100,
                february: 100,
                march: 100,
                april: 100,
                may: 100,
                june: 100,
                july: 100,
                august: 100,
                september: 100,
                october: 100,
                november: 100,
                december: 100,
              },
              {
                id: 'headquarters-electricity',
                name: '费用-电费',
                hierarchyRole: 'subjectDetail',
                functionalAttribute: '管理',
                annualTotal: 2400,
                january: 200,
                february: 200,
                march: 200,
                april: 200,
                may: 200,
                june: 200,
                july: 200,
                august: 200,
                september: 200,
                october: 200,
                november: 200,
                december: 200,
              },
              {
                id: 'headquarters-water',
                name: '费用-水费',
                hierarchyRole: 'subjectDetail',
                functionalAttribute: '管理',
                annualTotal: 3600,
                january: 300,
                february: 300,
                march: 300,
                april: 300,
                may: 300,
                june: 300,
                july: 300,
                august: 300,
                september: 300,
                october: 300,
                november: 300,
                december: 300,
              },
            ],
          },
        ],
      },
      {
        id: 'huajing',
        name: '华晶公司',
        hierarchyRole: 'businessUnit',
        functionalAttribute: '-',
        annualTotal: 28800,
        january: 2400,
        february: 2400,
        march: 2400,
        april: 2400,
        may: 2400,
        june: 2400,
        july: 2400,
        august: 2400,
        september: 2400,
        october: 2400,
        november: 2400,
        december: 2400,
        children: [
          {
            id: 'huajing-sales',
            name: '华晶公司-销售部',
            hierarchyRole: 'department',
            functionalAttribute: '-',
            annualTotal: 7200,
            january: 600,
            february: 600,
            march: 600,
            april: 600,
            may: 600,
            june: 600,
            july: 600,
            august: 600,
            september: 600,
            october: 600,
            november: 600,
            december: 600,
            regionSummaries: [
              {
                id: 'huajing-sales-expense-summary',
                name: '费用汇总',
                hierarchyRole: 'subjectSummary',
                functionalAttribute: '-',
                annualTotal: 7200,
                january: 600,
                february: 600,
                march: 600,
                april: 600,
                may: 600,
                june: 600,
                july: 600,
                august: 600,
                september: 600,
                october: 600,
                november: 600,
                december: 600,
                children: [
                  {
                    id: 'huajing-sales-subtotal',
                    name: '管理费用合计',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '-',
                    annualTotal: 7200,
                    january: 600,
                    february: 600,
                    march: 600,
                    april: 600,
                    may: 600,
                    june: 600,
                    july: 600,
                    august: 600,
                    september: 600,
                    october: 600,
                    november: 600,
                    december: 600,
                  },
                  {
                    id: 'huajing-sales-office',
                    name: '费用-办公费',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '销售',
                    annualTotal: 1200,
                    january: 100,
                    february: 100,
                    march: 100,
                    april: 100,
                    may: 100,
                    june: 100,
                    july: 100,
                    august: 100,
                    september: 100,
                    october: 100,
                    november: 100,
                    december: 100,
                  },
                  {
                    id: 'huajing-sales-electricity',
                    name: '费用-电费',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '销售',
                    annualTotal: 2400,
                    january: 200,
                    february: 200,
                    march: 200,
                    april: 200,
                    may: 200,
                    june: 200,
                    july: 200,
                    august: 200,
                    september: 200,
                    october: 200,
                    november: 200,
                    december: 200,
                  },
                  {
                    id: 'huajing-sales-water',
                    name: '费用-水费',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '销售',
                    annualTotal: 3600,
                    january: 300,
                    february: 300,
                    march: 300,
                    april: 300,
                    may: 300,
                    june: 300,
                    july: 300,
                    august: 300,
                    september: 300,
                    october: 300,
                    november: 300,
                    december: 300,
                  },
                ],
              },
            ],
          },
          {
            id: 'huajing-finance',
            name: '华晶公司-财务部',
            hierarchyRole: 'department',
            functionalAttribute: '-',
            annualTotal: 7200,
            january: 600,
            february: 600,
            march: 600,
            april: 600,
            may: 600,
            june: 600,
            july: 600,
            august: 600,
            september: 600,
            october: 600,
            november: 600,
            december: 600,
            regionSummaries: [
              {
                id: 'huajing-finance-expense-summary',
                name: '费用汇总',
                hierarchyRole: 'subjectSummary',
                functionalAttribute: '-',
                annualTotal: 7200,
                january: 600,
                february: 600,
                march: 600,
                april: 600,
                may: 600,
                june: 600,
                july: 600,
                august: 600,
                september: 600,
                october: 600,
                november: 600,
                december: 600,
                children: [
                  {
                    id: 'huajing-finance-subtotal',
                    name: '管理费用合计',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '-',
                    annualTotal: 7200,
                    january: 600,
                    february: 600,
                    march: 600,
                    april: 600,
                    may: 600,
                    june: 600,
                    july: 600,
                    august: 600,
                    september: 600,
                    october: 600,
                    november: 600,
                    december: 600,
                  },
                  {
                    id: 'huajing-finance-office',
                    name: '费用-办公费',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '销售',
                    annualTotal: 1200,
                    january: 100,
                    february: 100,
                    march: 100,
                    april: 100,
                    may: 100,
                    june: 100,
                    july: 100,
                    august: 100,
                    september: 100,
                    october: 100,
                    november: 100,
                    december: 100,
                  },
                  {
                    id: 'huajing-finance-electricity',
                    name: '费用-电费',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '销售',
                    annualTotal: 2400,
                    january: 200,
                    february: 200,
                    march: 200,
                    april: 200,
                    may: 200,
                    june: 200,
                    july: 200,
                    august: 200,
                    september: 200,
                    october: 200,
                    november: 200,
                    december: 200,
                  },
                  {
                    id: 'huajing-finance-water',
                    name: '费用-水费',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '销售',
                    annualTotal: 3600,
                    january: 300,
                    february: 300,
                    march: 300,
                    april: 300,
                    may: 300,
                    june: 300,
                    july: 300,
                    august: 300,
                    september: 300,
                    october: 300,
                    november: 300,
                    december: 300,
                  },
                ],
              },
            ],
          },
          {
            id: 'huajing-administration',
            name: '华晶公司-行政部',
            hierarchyRole: 'department',
            functionalAttribute: '-',
            annualTotal: 7200,
            january: 600,
            february: 600,
            march: 600,
            april: 600,
            may: 600,
            june: 600,
            july: 600,
            august: 600,
            september: 600,
            october: 600,
            november: 600,
            december: 600,
            regionSummaries: [
              {
                id: 'huajing-administration-expense-summary',
                name: '费用汇总',
                hierarchyRole: 'subjectSummary',
                functionalAttribute: '-',
                annualTotal: 7200,
                january: 600,
                february: 600,
                march: 600,
                april: 600,
                may: 600,
                june: 600,
                july: 600,
                august: 600,
                september: 600,
                october: 600,
                november: 600,
                december: 600,
                children: [
                  {
                    id: 'huajing-administration-subtotal',
                    name: '日常费用合计',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '-',
                    annualTotal: 7200,
                    january: 600,
                    february: 600,
                    march: 600,
                    april: 600,
                    may: 600,
                    june: 600,
                    july: 600,
                    august: 600,
                    september: 600,
                    october: 600,
                    november: 600,
                    december: 600,
                  },
                  {
                    id: 'huajing-administration-office',
                    name: '费用-办公费',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '管理',
                    annualTotal: 1200,
                    january: 100,
                    february: 100,
                    march: 100,
                    april: 100,
                    may: 100,
                    june: 100,
                    july: 100,
                    august: 100,
                    september: 100,
                    october: 100,
                    november: 100,
                    december: 100,
                  },
                  {
                    id: 'huajing-administration-electricity',
                    name: '费用-电费',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '管理',
                    annualTotal: 2400,
                    january: 200,
                    february: 200,
                    march: 200,
                    april: 200,
                    may: 200,
                    june: 200,
                    july: 200,
                    august: 200,
                    september: 200,
                    october: 200,
                    november: 200,
                    december: 200,
                  },
                  {
                    id: 'huajing-administration-water',
                    name: '费用-水费',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '管理',
                    annualTotal: 3600,
                    january: 300,
                    february: 300,
                    march: 300,
                    april: 300,
                    may: 300,
                    june: 300,
                    july: 300,
                    august: 300,
                    september: 300,
                    october: 300,
                    november: 300,
                    december: 300,
                  },
                ],
              },
            ],
          },
          {
            id: 'huajing-research',
            name: '华晶公司-研发部',
            hierarchyRole: 'department',
            functionalAttribute: '-',
            annualTotal: 7200,
            january: 600,
            february: 600,
            march: 600,
            april: 600,
            may: 600,
            june: 600,
            july: 600,
            august: 600,
            september: 600,
            october: 600,
            november: 600,
            december: 600,
            regionSummaries: [
              {
                id: 'huajing-research-expense-summary',
                name: '费用汇总',
                hierarchyRole: 'subjectSummary',
                functionalAttribute: '-',
                annualTotal: 7200,
                january: 600,
                february: 600,
                march: 600,
                april: 600,
                may: 600,
                june: 600,
                july: 600,
                august: 600,
                september: 600,
                october: 600,
                november: 600,
                december: 600,
                children: [
                  {
                    id: 'huajing-research-subtotal',
                    name: '日常费用合计',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '-',
                    annualTotal: 7200,
                    january: 600,
                    february: 600,
                    march: 600,
                    april: 600,
                    may: 600,
                    june: 600,
                    july: 600,
                    august: 600,
                    september: 600,
                    october: 600,
                    november: 600,
                    december: 600,
                  },
                  {
                    id: 'huajing-research-office',
                    name: '费用-办公费',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '研发',
                    annualTotal: 1200,
                    january: 100,
                    february: 100,
                    march: 100,
                    april: 100,
                    may: 100,
                    june: 100,
                    july: 100,
                    august: 100,
                    september: 100,
                    october: 100,
                    november: 100,
                    december: 100,
                  },
                  {
                    id: 'huajing-research-electricity',
                    name: '费用-电费',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '研发',
                    annualTotal: 2400,
                    january: 200,
                    february: 200,
                    march: 200,
                    april: 200,
                    may: 200,
                    june: 200,
                    july: 200,
                    august: 200,
                    september: 200,
                    october: 200,
                    november: 200,
                    december: 200,
                  },
                  {
                    id: 'huajing-research-water',
                    name: '费用-水费',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '研发',
                    annualTotal: 3600,
                    january: 300,
                    february: 300,
                    march: 300,
                    april: 300,
                    may: 300,
                    june: 300,
                    july: 300,
                    august: 300,
                    september: 300,
                    october: 300,
                    november: 300,
                    december: 300,
                  },
                ],
              },
            ],
          },
        ],
        regionSummaries: [
          {
            id: 'huajing-expense-summary',
            name: '费用汇总',
            hierarchyRole: 'subjectSummary',
            functionalAttribute: '-',
            annualTotal: 28800,
            january: 2400,
            february: 2400,
            march: 2400,
            april: 2400,
            may: 2400,
            june: 2400,
            july: 2400,
            august: 2400,
            september: 2400,
            october: 2400,
            november: 2400,
            december: 2400,
            children: [
              {
                id: 'huajing-subtotal',
                name: '日常费用合计',
                hierarchyRole: 'subjectDetail',
                functionalAttribute: '-',
                annualTotal: 28800,
                january: 2400,
                february: 2400,
                march: 2400,
                april: 2400,
                may: 2400,
                june: 2400,
                july: 2400,
                august: 2400,
                september: 2400,
                october: 2400,
                november: 2400,
                december: 2400,
              },
              {
                id: 'huajing-office',
                name: '费用-办公费',
                hierarchyRole: 'subjectDetail',
                functionalAttribute: '管理',
                annualTotal: 4800,
                january: 400,
                february: 400,
                march: 400,
                april: 400,
                may: 400,
                june: 400,
                july: 400,
                august: 400,
                september: 400,
                october: 400,
                november: 400,
                december: 400,
              },
              {
                id: 'huajing-electricity',
                name: '费用-电费',
                hierarchyRole: 'subjectDetail',
                functionalAttribute: '管理',
                annualTotal: 9600,
                january: 800,
                february: 800,
                march: 800,
                april: 800,
                may: 800,
                june: 800,
                july: 800,
                august: 800,
                september: 800,
                october: 800,
                november: 800,
                december: 800,
              },
              {
                id: 'huajing-water',
                name: '费用-水费',
                hierarchyRole: 'subjectDetail',
                functionalAttribute: '管理',
                annualTotal: 14400,
                january: 1200,
                february: 1200,
                march: 1200,
                april: 1200,
                may: 1200,
                june: 1200,
                july: 1200,
                august: 1200,
                september: 1200,
                october: 1200,
                november: 1200,
                december: 1200,
              },
            ],
          },
        ],
      },
      {
        id: 'shanghua',
        name: '上华公司',
        hierarchyRole: 'businessUnit',
        functionalAttribute: '-',
        annualTotal: 7200,
        january: 600,
        february: 600,
        march: 600,
        april: 600,
        may: 600,
        june: 600,
        july: 600,
        august: 600,
        september: 600,
        october: 600,
        november: 600,
        december: 600,
        children: [
          {
            id: 'shanghua-sales',
            name: '上华公司-销售部',
            hierarchyRole: 'department',
            functionalAttribute: '-',
            annualTotal: 7200,
            january: 600,
            february: 600,
            march: 600,
            april: 600,
            may: 600,
            june: 600,
            july: 600,
            august: 600,
            september: 600,
            october: 600,
            november: 600,
            december: 600,
            regionSummaries: [
              {
                id: 'shanghua-sales-expense-summary',
                name: '费用汇总',
                hierarchyRole: 'subjectSummary',
                functionalAttribute: '-',
                annualTotal: 7200,
                january: 600,
                february: 600,
                march: 600,
                april: 600,
                may: 600,
                june: 600,
                july: 600,
                august: 600,
                september: 600,
                october: 600,
                november: 600,
                december: 600,
                children: [
                  {
                    id: 'shanghua-sales-subtotal',
                    name: '日常费用合计',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '-',
                    annualTotal: 7200,
                    january: 600,
                    february: 600,
                    march: 600,
                    april: 600,
                    may: 600,
                    june: 600,
                    july: 600,
                    august: 600,
                    september: 600,
                    october: 600,
                    november: 600,
                    december: 600,
                  },
                  {
                    id: 'shanghua-sales-office',
                    name: '费用-办公费',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '销售',
                    annualTotal: 1200,
                    january: 100,
                    february: 100,
                    march: 100,
                    april: 100,
                    may: 100,
                    june: 100,
                    july: 100,
                    august: 100,
                    september: 100,
                    october: 100,
                    november: 100,
                    december: 100,
                  },
                  {
                    id: 'shanghua-sales-electricity',
                    name: '费用-电费',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '销售',
                    annualTotal: 2400,
                    january: 200,
                    february: 200,
                    march: 200,
                    april: 200,
                    may: 200,
                    june: 200,
                    july: 200,
                    august: 200,
                    september: 200,
                    october: 200,
                    november: 200,
                    december: 200,
                  },
                  {
                    id: 'shanghua-sales-water',
                    name: '费用-水费',
                    hierarchyRole: 'subjectDetail',
                    functionalAttribute: '销售',
                    annualTotal: 3600,
                    january: 300,
                    february: 300,
                    march: 300,
                    april: 300,
                    may: 300,
                    june: 300,
                    july: 300,
                    august: 300,
                    september: 300,
                    october: 300,
                    november: 300,
                    december: 300,
                  },
                ],
              },
            ],
          },
        ],
        regionSummaries: [
          {
            id: 'shanghua-expense-summary',
            name: '费用汇总',
            hierarchyRole: 'subjectSummary',
            functionalAttribute: '-',
            annualTotal: 7200,
            january: 600,
            february: 600,
            march: 600,
            april: 600,
            may: 600,
            june: 600,
            july: 600,
            august: 600,
            september: 600,
            october: 600,
            november: 600,
            december: 600,
            children: [
              {
                id: 'shanghua-subtotal',
                name: '日常费用合计',
                hierarchyRole: 'subjectDetail',
                functionalAttribute: '-',
                annualTotal: 7200,
                january: 600,
                february: 600,
                march: 600,
                april: 600,
                may: 600,
                june: 600,
                july: 600,
                august: 600,
                september: 600,
                october: 600,
                november: 600,
                december: 600,
              },
              {
                id: 'shanghua-office',
                name: '费用-办公费',
                hierarchyRole: 'subjectDetail',
                functionalAttribute: '管理',
                annualTotal: 1200,
                january: 100,
                february: 100,
                march: 100,
                april: 100,
                may: 100,
                june: 100,
                july: 100,
                august: 100,
                september: 100,
                october: 100,
                november: 100,
                december: 100,
              },
              {
                id: 'shanghua-electricity',
                name: '费用-电费',
                hierarchyRole: 'subjectDetail',
                functionalAttribute: '管理',
                annualTotal: 2400,
                january: 200,
                february: 200,
                march: 200,
                april: 200,
                may: 200,
                june: 200,
                july: 200,
                august: 200,
                september: 200,
                october: 200,
                november: 200,
                december: 200,
              },
              {
                id: 'shanghua-water',
                name: '费用-水费',
                hierarchyRole: 'subjectDetail',
                functionalAttribute: '管理',
                annualTotal: 3600,
                january: 300,
                february: 300,
                march: 300,
                april: 300,
                may: 300,
                june: 300,
                july: 300,
                august: 300,
                september: 300,
                october: 300,
                november: 300,
                december: 300,
              },
            ],
          },
        ],
      },
    ],
    regionSummaries: [
      {
        id: 'cr-micro-group-expense-summary',
        name: '费用汇总',
        hierarchyRole: 'subjectSummary',
        functionalAttribute: '-',
        annualTotal: 43200,
        january: 3600,
        february: 3600,
        march: 3600,
        april: 3600,
        may: 3600,
        june: 3600,
        july: 3600,
        august: 3600,
        september: 3600,
        october: 3600,
        november: 3600,
        december: 3600,
        children: [
          {
            id: 'cr-micro-group-subtotal',
            name: '日常费用合计',
            hierarchyRole: 'subjectDetail',
            functionalAttribute: '-',
            annualTotal: 43200,
            january: 3600,
            february: 3600,
            march: 3600,
            april: 3600,
            may: 3600,
            june: 3600,
            july: 3600,
            august: 3600,
            september: 3600,
            october: 3600,
            november: 3600,
            december: 3600,
          },
          {
            id: 'cr-micro-group-office',
            name: '费用-办公费',
            hierarchyRole: 'subjectDetail',
            functionalAttribute: '管理',
            annualTotal: 7200,
            january: 600,
            february: 600,
            march: 600,
            april: 600,
            may: 600,
            june: 600,
            july: 600,
            august: 600,
            september: 600,
            october: 600,
            november: 600,
            december: 600,
          },
          {
            id: 'cr-micro-group-electricity',
            name: '费用-电费',
            hierarchyRole: 'subjectDetail',
            functionalAttribute: '管理',
            annualTotal: 14400,
            january: 1200,
            february: 1200,
            march: 1200,
            april: 1200,
            may: 1200,
            june: 1200,
            july: 1200,
            august: 1200,
            september: 1200,
            october: 1200,
            november: 1200,
            december: 1200,
          },
          {
            id: 'cr-micro-group-water',
            name: '费用-水费',
            hierarchyRole: 'subjectDetail',
            functionalAttribute: '管理',
            annualTotal: 21600,
            january: 1800,
            february: 1800,
            march: 1800,
            april: 1800,
            may: 1800,
            june: 1800,
            july: 1800,
            august: 1800,
            september: 1800,
            october: 1800,
            november: 1800,
            december: 1800,
          },
        ],
      },
    ],
  },
];
