const BUSINESS_COLUMN_DATA = [
  {
    id: 'business-dimensions',
    label: '业务维度',
    frozen: true,
    children: [
      {
        id: 'product-hierarchy',
        field: 'productHierarchy',
        label: '产品层级',
        width: 178,
        dataType: 'string',
        editable: false,
        searchable: true,
      },
      {
        id: 'product-attribute',
        field: 'productAttribute',
        label: '产品属性',
        width: 144,
        dataType: 'string',
        editable: false,
        searchable: true,
      },
      {
        id: 'region-hierarchy',
        field: 'regionHierarchy',
        label: '区域层级',
        width: 168,
        dataType: 'string',
        editable: false,
        searchable: true,
      },
    ],
  },
  {
    id: 'core-metrics',
    label: '核心经营指标',
    summaryField: 'revenue',
    children: [
      {
        id: 'income-metrics',
        label: '收入指标',
        summaryField: 'revenue',
        children: [
          {
            id: 'revenue',
            field: 'revenue',
            label: '净收入',
            width: 112,
            dataType: 'number',
            format: 'currency',
            editor: {
              type: 'number',
            },
            editable: true,
          },
          {
            id: 'product-revenue',
            field: 'productRevenue',
            label: '商品收入',
            width: 108,
            dataType: 'number',
            format: 'currency',
            editor: {
              type: 'number',
            },
            editable: true,
          },
          {
            id: 'service-revenue',
            field: 'serviceRevenue',
            label: '服务收入',
            width: 108,
            dataType: 'number',
            format: 'currency',
            editor: {
              type: 'number',
            },
            editable: true,
          },
        ],
      },
      {
        id: 'order-metrics',
        label: '订单指标',
        summaryField: 'orders',
        children: [
          {
            id: 'orders',
            field: 'orders',
            label: '订单数',
            width: 92,
            dataType: 'number',
            format: 'integer',
            editor: {
              type: 'number',
            },
            editable: true,
          },
          {
            id: 'online-orders',
            field: 'onlineOrders',
            label: '线上订单',
            width: 92,
            dataType: 'number',
            format: 'integer',
            editor: {
              type: 'number',
            },
            editable: true,
          },
          {
            id: 'offline-orders',
            field: 'offlineOrders',
            label: '线下订单',
            width: 92,
            dataType: 'number',
            format: 'integer',
            editor: {
              type: 'number',
            },
            editable: true,
          },
          {
            id: 'average-order',
            field: 'avgOrder',
            label: '客单价',
            width: 98,
            dataType: 'number',
            format: 'currency',
            editable: false,
          },
        ],
      },
      {
        id: 'target-management',
        label: '目标管理',
        children: [
          {
            id: 'completion',
            field: 'completion',
            label: '目标达成',
            width: 96,
            dataType: 'number',
            format: 'percent',
            editor: {
              type: 'number',
            },
            editable: true,
          },
        ],
      },
    ],
  },
  {
    id: 'business-governance',
    label: '业务治理',
    summaryField: 'owner',
    children: [
      {
        id: 'responsibility-verification',
        label: '责任与核验',
        summaryField: 'owner',
        children: [
          {
            id: 'owner',
            field: 'owner',
            label: '负责人',
            width: 84,
            dataType: 'string',
            editor: {
              type: 'text',
            },
            editable: true,
            searchable: true,
          },
          {
            id: 'status',
            field: 'status',
            label: '核验状态',
            width: 96,
            dataType: 'string',
            editor: {
              type: 'select',
              options: ['已核验', '待复核', '异常'],
            },
            editable: true,
            searchable: true,
          },
          {
            id: 'verified',
            field: 'verified',
            label: '已核验',
            width: 82,
            dataType: 'boolean',
            editor: {
              type: 'checkbox',
            },
            editable: true,
            searchable: true,
          },
        ],
      },
      {
        id: 'record-information',
        label: '记录信息',
        children: [
          {
            id: 'updated-at',
            field: 'updatedAt',
            label: '更新日期',
            width: 104,
            dataType: 'date',
            format: 'date',
            editor: {
              type: 'date',
            },
            editable: true,
            searchable: true,
          },
          {
            id: 'adjustment-factor',
            field: 'adjustmentFactor',
            label: '调整系数',
            width: 96,
            dataType: 'number',
            format: 'decimal',
            editor: {
              type: 'number',
            },
            editable: true,
          },
        ],
      },
    ],
  },
];

const BUSINESS_DATA = [
  {
    id: 'furniture',
    name: '家具',
    hierarchyRole: 'category',
    revenue: 15099200,
    productRevenue: 11777376,
    serviceRevenue: 3321824,
    orders: 2736,
    onlineOrders: 1724,
    offlineOrders: 1012,
    avgOrder: 5519,
    completion: 0.927875,
    adjustmentFactor: 0.88,
    owner: '林嘉',
    status: '已核验',
    verified: true,
    updatedAt: '2026-08-20T16:00:00.000Z',
    children: [
      {
        id: 'furniture-bookcases',
        name: '书柜',
        hierarchyRole: 'subcategory',
        revenue: 6018000,
        productRevenue: 4694040,
        serviceRevenue: 1323960,
        orders: 1090,
        onlineOrders: 687,
        offlineOrders: 403,
        avgOrder: 5521,
        completion: 0.944,
        adjustmentFactor: 0.85,
        owner: '林嘉',
        status: '已核验',
        verified: true,
        updatedAt: '2026-08-20T16:00:00.000Z',
        children: [
          {
            id: 'bookcases-east',
            name: '华东',
            hierarchyRole: 'region',
            revenue: 3724800,
            productRevenue: 2905344,
            serviceRevenue: 819456,
            orders: 646,
            onlineOrders: 407,
            offlineOrders: 239,
            avgOrder: 5766,
            completion: 0.9675,
            adjustmentFactor: 1.06,
            owner: '周宁',
            status: '已核验',
            verified: true,
            updatedAt: '2026-08-20T16:00:00.000Z',
            children: [
              {
                id: 'bookcases-shanghai',
                name: '上海',
                hierarchyRole: 'detail',
                revenue: 2086400,
                productRevenue: 1627392,
                serviceRevenue: 459008,
                orders: 352,
                onlineOrders: 222,
                offlineOrders: 130,
                avgOrder: 5927,
                completion: 0.982,
                owner: '杨晨',
                status: '已核验',
                verified: true,
                updatedAt: '2026-08-20T16:00:00.000Z',
                adjustmentFactor: 0.91,
              },
              {
                id: 'bookcases-jiangsu',
                name: '江苏',
                hierarchyRole: 'detail',
                revenue: 1638400,
                productRevenue: 1277952,
                serviceRevenue: 360448,
                orders: 294,
                onlineOrders: 185,
                offlineOrders: 109,
                avgOrder: 5573,
                completion: 0.953,
                owner: '陈叶',
                status: '待复核',
                verified: false,
                updatedAt: '2026-08-20T16:00:00.000Z',
                adjustmentFactor: 0.95,
              },
            ],
          },
          {
            id: 'bookcases-central',
            name: '华中',
            hierarchyRole: 'region',
            revenue: 2293200,
            productRevenue: 1788696,
            serviceRevenue: 504504,
            orders: 444,
            onlineOrders: 280,
            offlineOrders: 164,
            avgOrder: 5165,
            completion: 0.9205,
            adjustmentFactor: 0.9,
            owner: '赵敏',
            status: '已核验',
            verified: true,
            updatedAt: '2026-08-20T16:00:00.000Z',
            children: [
              {
                id: 'bookcases-hubei',
                name: '湖北',
                hierarchyRole: 'detail',
                revenue: 1286600,
                productRevenue: 1003548,
                serviceRevenue: 283052,
                orders: 238,
                onlineOrders: 150,
                offlineOrders: 88,
                avgOrder: 5406,
                completion: 0.942,
                owner: '孙毅',
                status: '已核验',
                verified: true,
                updatedAt: '2026-08-20T16:00:00.000Z',
                adjustmentFactor: 1.01,
              },
              {
                id: 'bookcases-henan',
                name: '河南',
                hierarchyRole: 'detail',
                revenue: 1006600,
                productRevenue: 785148,
                serviceRevenue: 221452,
                orders: 206,
                onlineOrders: 130,
                offlineOrders: 76,
                avgOrder: 4886,
                completion: 0.899,
                owner: '徐昕',
                status: '待复核',
                verified: false,
                updatedAt: '2026-08-19T16:00:00.000Z',
                adjustmentFactor: 1,
              },
            ],
          },
        ],
      },
      {
        id: 'furniture-chairs',
        name: '座椅',
        hierarchyRole: 'subcategory',
        revenue: 9081200,
        productRevenue: 7083336,
        serviceRevenue: 1997864,
        orders: 1646,
        onlineOrders: 1037,
        offlineOrders: 609,
        avgOrder: 5517,
        completion: 0.91175,
        adjustmentFactor: 0.83,
        owner: '林嘉',
        status: '已核验',
        verified: true,
        updatedAt: '2026-08-20T16:00:00.000Z',
        children: [
          {
            id: 'chairs-east',
            name: '华东',
            hierarchyRole: 'region',
            revenue: 4267000,
            productRevenue: 3328260,
            serviceRevenue: 938740,
            orders: 728,
            onlineOrders: 459,
            offlineOrders: 269,
            avgOrder: 5861,
            completion: 0.919,
            adjustmentFactor: 0.95,
            owner: '周宁',
            status: '已核验',
            verified: true,
            updatedAt: '2026-08-20T16:00:00.000Z',
            children: [
              {
                id: 'chairs-zhejiang',
                name: '浙江',
                hierarchyRole: 'detail',
                revenue: 2483500,
                productRevenue: 1937130,
                serviceRevenue: 546370,
                orders: 414,
                onlineOrders: 261,
                offlineOrders: 153,
                avgOrder: 5999,
                completion: 0.934,
                owner: '吴哲',
                status: '已核验',
                verified: true,
                updatedAt: '2026-08-19T16:00:00.000Z',
                adjustmentFactor: 0.91,
              },
              {
                id: 'chairs-anhui',
                name: '安徽',
                hierarchyRole: 'detail',
                revenue: 1783500,
                productRevenue: 1391130,
                serviceRevenue: 392370,
                orders: 314,
                onlineOrders: 198,
                offlineOrders: 116,
                avgOrder: 5680,
                completion: 0.904,
                owner: '韩睿',
                status: '已核验',
                verified: true,
                updatedAt: '2026-08-19T16:00:00.000Z',
                adjustmentFactor: 0.84,
              },
            ],
          },
          {
            id: 'chairs-south',
            name: '华南',
            hierarchyRole: 'region',
            revenue: 4814200,
            productRevenue: 3755076,
            serviceRevenue: 1059124,
            orders: 918,
            onlineOrders: 578,
            offlineOrders: 340,
            avgOrder: 5244,
            completion: 0.9045,
            adjustmentFactor: 0.99,
            owner: '苏然',
            status: '已核验',
            verified: true,
            updatedAt: '2026-08-20T16:00:00.000Z',
            children: [
              {
                id: 'chairs-guangdong',
                name: '广东',
                hierarchyRole: 'detail',
                revenue: 3286400,
                productRevenue: 2563392,
                serviceRevenue: 723008,
                orders: 596,
                onlineOrders: 375,
                offlineOrders: 221,
                avgOrder: 5514,
                completion: 0.928,
                owner: '黄清',
                status: '待复核',
                verified: false,
                updatedAt: '2026-08-20T16:00:00.000Z',
                adjustmentFactor: 0.87,
              },
              {
                id: 'chairs-fujian',
                name: '福建',
                hierarchyRole: 'detail',
                revenue: 1527800,
                productRevenue: 1191684,
                serviceRevenue: 336116,
                orders: 322,
                onlineOrders: 203,
                offlineOrders: 119,
                avgOrder: 4745,
                completion: 0.881,
                owner: '罗蔚',
                status: '已核验',
                verified: true,
                updatedAt: '2026-08-19T16:00:00.000Z',
                adjustmentFactor: 0.92,
              },
            ],
          },
        ],
      },
    ],
    regionSummaries: [
      {
        id: 'furniture-summary-east',
        name: '华东',
        hierarchyRole: 'region',
        revenue: 7991800,
        productRevenue: 6233604,
        serviceRevenue: 1758196,
        orders: 1374,
        onlineOrders: 866,
        offlineOrders: 508,
        avgOrder: 5816,
        completion: 0.9437314497359793,
        owner: '林嘉',
        status: '待复核',
        verified: false,
        updatedAt: '2026-08-20T16:00:00.000Z',
        adjustmentFactor: 0.9,
        detailIds: [
          'bookcases-shanghai',
          'bookcases-jiangsu',
          'chairs-zhejiang',
          'chairs-anhui',
        ],
      },
      {
        id: 'furniture-summary-central',
        name: '华中',
        hierarchyRole: 'region',
        revenue: 2293200,
        productRevenue: 1788696,
        serviceRevenue: 504504,
        orders: 444,
        onlineOrders: 280,
        offlineOrders: 164,
        avgOrder: 5165,
        completion: 0.9231251526251527,
        owner: '林嘉',
        status: '待复核',
        verified: false,
        updatedAt: '2026-08-20T16:00:00.000Z',
        adjustmentFactor: 1,
        detailIds: ['bookcases-hubei', 'bookcases-henan'],
      },
      {
        id: 'furniture-summary-south',
        name: '华南',
        hierarchyRole: 'region',
        revenue: 4814200,
        productRevenue: 3755076,
        serviceRevenue: 1059124,
        orders: 918,
        onlineOrders: 578,
        offlineOrders: 340,
        avgOrder: 5244,
        completion: 0.9130844169332392,
        owner: '林嘉',
        status: '待复核',
        verified: false,
        updatedAt: '2026-08-20T16:00:00.000Z',
        adjustmentFactor: 0.9,
        detailIds: ['chairs-guangdong', 'chairs-fujian'],
      },
    ],
  },
  {
    id: 'office-supplies',
    name: '办公用品',
    hierarchyRole: 'category',
    revenue: 11399200,
    productRevenue: 8891376,
    serviceRevenue: 2507824,
    orders: 2906,
    onlineOrders: 1831,
    offlineOrders: 1075,
    avgOrder: 3923,
    completion: 0.916625,
    adjustmentFactor: 1.03,
    owner: '罗蔚',
    status: '待复核',
    verified: false,
    updatedAt: '2026-08-20T16:00:00.000Z',
    children: [
      {
        id: 'office-paper',
        name: '纸品',
        hierarchyRole: 'subcategory',
        revenue: 5218000,
        productRevenue: 4070040,
        serviceRevenue: 1147960,
        orders: 1450,
        onlineOrders: 914,
        offlineOrders: 536,
        avgOrder: 3599,
        completion: 0.9315,
        adjustmentFactor: 1.04,
        owner: '罗蔚',
        status: '已核验',
        verified: true,
        updatedAt: '2026-08-20T16:00:00.000Z',
        children: [
          {
            id: 'paper-east',
            name: '华东',
            hierarchyRole: 'region',
            revenue: 2624800,
            productRevenue: 2047344,
            serviceRevenue: 577456,
            orders: 786,
            onlineOrders: 495,
            offlineOrders: 291,
            avgOrder: 3339,
            completion: 0.9575,
            adjustmentFactor: 0.91,
            owner: '周宁',
            status: '已核验',
            verified: true,
            updatedAt: '2026-08-20T16:00:00.000Z',
            children: [
              {
                id: 'paper-shanghai',
                name: '上海',
                hierarchyRole: 'detail',
                revenue: 1486400,
                productRevenue: 1159392,
                serviceRevenue: 327008,
                orders: 442,
                onlineOrders: 278,
                offlineOrders: 164,
                avgOrder: 3363,
                completion: 0.972,
                owner: '杨晨',
                status: '已核验',
                verified: true,
                updatedAt: '2026-08-20T16:00:00.000Z',
                adjustmentFactor: 0.88,
              },
              {
                id: 'paper-nanjing',
                name: '南京',
                hierarchyRole: 'detail',
                revenue: 1138400,
                productRevenue: 887952,
                serviceRevenue: 250448,
                orders: 344,
                onlineOrders: 217,
                offlineOrders: 127,
                avgOrder: 3309,
                completion: 0.943,
                owner: '陈叶',
                status: '待复核',
                verified: false,
                updatedAt: '2026-08-20T16:00:00.000Z',
                adjustmentFactor: 0.83,
              },
            ],
          },
          {
            id: 'paper-north',
            name: '华北',
            hierarchyRole: 'region',
            revenue: 2593200,
            productRevenue: 2022696,
            serviceRevenue: 570504,
            orders: 664,
            onlineOrders: 418,
            offlineOrders: 246,
            avgOrder: 3905,
            completion: 0.9055,
            adjustmentFactor: 0.93,
            owner: '赵敏',
            status: '已核验',
            verified: true,
            updatedAt: '2026-08-20T16:00:00.000Z',
            children: [
              {
                id: 'paper-beijing',
                name: '北京',
                hierarchyRole: 'detail',
                revenue: 1686600,
                productRevenue: 1315548,
                serviceRevenue: 371052,
                orders: 408,
                onlineOrders: 257,
                offlineOrders: 151,
                avgOrder: 4134,
                completion: 0.922,
                owner: '孙毅',
                status: '已核验',
                verified: true,
                updatedAt: '2026-08-20T16:00:00.000Z',
                adjustmentFactor: 0.85,
              },
              {
                id: 'paper-tianjin',
                name: '天津',
                hierarchyRole: 'detail',
                revenue: 906600,
                productRevenue: 707148,
                serviceRevenue: 199452,
                orders: 256,
                onlineOrders: 161,
                offlineOrders: 95,
                avgOrder: 3541,
                completion: 0.889,
                owner: '徐昕',
                status: '待复核',
                verified: false,
                updatedAt: '2026-08-19T16:00:00.000Z',
                adjustmentFactor: 0.88,
              },
            ],
          },
        ],
      },
      {
        id: 'office-storage',
        name: '收纳',
        hierarchyRole: 'subcategory',
        revenue: 6181200,
        productRevenue: 4821336,
        serviceRevenue: 1359864,
        orders: 1456,
        onlineOrders: 917,
        offlineOrders: 539,
        avgOrder: 4245,
        completion: 0.90175,
        adjustmentFactor: 1.1,
        owner: '罗蔚',
        status: '已核验',
        verified: true,
        updatedAt: '2026-08-20T16:00:00.000Z',
        children: [
          {
            id: 'storage-central',
            name: '华中',
            hierarchyRole: 'region',
            revenue: 2767000,
            productRevenue: 2158260,
            serviceRevenue: 608740,
            orders: 658,
            onlineOrders: 415,
            offlineOrders: 243,
            avgOrder: 4205,
            completion: 0.909,
            adjustmentFactor: 0.87,
            owner: '周宁',
            status: '已核验',
            verified: true,
            updatedAt: '2026-08-20T16:00:00.000Z',
            children: [
              {
                id: 'storage-wuhan',
                name: '武汉',
                hierarchyRole: 'detail',
                revenue: 1583500,
                productRevenue: 1235130,
                serviceRevenue: 348370,
                orders: 374,
                onlineOrders: 236,
                offlineOrders: 138,
                avgOrder: 4234,
                completion: 0.924,
                owner: '吴哲',
                status: '已核验',
                verified: true,
                updatedAt: '2026-08-19T16:00:00.000Z',
                adjustmentFactor: 0.82,
              },
              {
                id: 'storage-changsha',
                name: '长沙',
                hierarchyRole: 'detail',
                revenue: 1183500,
                productRevenue: 923130,
                serviceRevenue: 260370,
                orders: 284,
                onlineOrders: 179,
                offlineOrders: 105,
                avgOrder: 4167,
                completion: 0.894,
                owner: '韩睿',
                status: '已核验',
                verified: true,
                updatedAt: '2026-08-19T16:00:00.000Z',
                adjustmentFactor: 0.85,
              },
            ],
          },
          {
            id: 'storage-south',
            name: '华南',
            hierarchyRole: 'region',
            revenue: 3414200,
            productRevenue: 2663076,
            serviceRevenue: 751124,
            orders: 798,
            onlineOrders: 503,
            offlineOrders: 295,
            avgOrder: 4278,
            completion: 0.8945,
            adjustmentFactor: 1.03,
            owner: '苏然',
            status: '已核验',
            verified: true,
            updatedAt: '2026-08-20T16:00:00.000Z',
            children: [
              {
                id: 'storage-shenzhen',
                name: '深圳',
                hierarchyRole: 'detail',
                revenue: 2186400,
                productRevenue: 1705392,
                serviceRevenue: 481008,
                orders: 496,
                onlineOrders: 312,
                offlineOrders: 184,
                avgOrder: 4408,
                completion: 0.918,
                owner: '黄清',
                status: '待复核',
                verified: false,
                updatedAt: '2026-08-20T16:00:00.000Z',
                adjustmentFactor: 0.8,
              },
              {
                id: 'storage-xiamen',
                name: '厦门',
                hierarchyRole: 'detail',
                revenue: 1227800,
                productRevenue: 957684,
                serviceRevenue: 270116,
                orders: 302,
                onlineOrders: 190,
                offlineOrders: 112,
                avgOrder: 4066,
                completion: 0.871,
                owner: '罗蔚',
                status: '已核验',
                verified: true,
                updatedAt: '2026-08-19T16:00:00.000Z',
                adjustmentFactor: 1.03,
              },
            ],
          },
        ],
      },
    ],
    regionSummaries: [
      {
        id: 'office-supplies-summary-east',
        name: '华东',
        hierarchyRole: 'region',
        revenue: 2624800,
        productRevenue: 2047344,
        serviceRevenue: 577456,
        orders: 786,
        onlineOrders: 495,
        offlineOrders: 291,
        avgOrder: 3339,
        completion: 0.9594224321853093,
        owner: '罗蔚',
        status: '待复核',
        verified: false,
        updatedAt: '2026-08-20T16:00:00.000Z',
        adjustmentFactor: 0.85,
        detailIds: ['paper-shanghai', 'paper-nanjing'],
      },
      {
        id: 'office-supplies-summary-north',
        name: '华北',
        hierarchyRole: 'region',
        revenue: 2593200,
        productRevenue: 2022696,
        serviceRevenue: 570504,
        orders: 664,
        onlineOrders: 418,
        offlineOrders: 246,
        avgOrder: 3905,
        completion: 0.9104629801018047,
        owner: '罗蔚',
        status: '待复核',
        verified: false,
        updatedAt: '2026-08-20T16:00:00.000Z',
        adjustmentFactor: 0.86,
        detailIds: ['paper-beijing', 'paper-tianjin'],
      },
      {
        id: 'office-supplies-summary-central',
        name: '华中',
        hierarchyRole: 'region',
        revenue: 2767000,
        productRevenue: 2158260,
        serviceRevenue: 608740,
        orders: 658,
        onlineOrders: 415,
        offlineOrders: 243,
        avgOrder: 4205,
        completion: 0.9111684134441633,
        owner: '罗蔚',
        status: '已核验',
        verified: true,
        updatedAt: '2026-08-19T16:00:00.000Z',
        adjustmentFactor: 0.83,
        detailIds: ['storage-wuhan', 'storage-changsha'],
      },
      {
        id: 'office-supplies-summary-south',
        name: '华南',
        hierarchyRole: 'region',
        revenue: 3414200,
        productRevenue: 2663076,
        serviceRevenue: 751124,
        orders: 798,
        onlineOrders: 502,
        offlineOrders: 296,
        avgOrder: 4278,
        completion: 0.9010980610391892,
        owner: '罗蔚',
        status: '待复核',
        verified: false,
        updatedAt: '2026-08-20T16:00:00.000Z',
        adjustmentFactor: 0.92,
        detailIds: ['storage-shenzhen', 'storage-xiamen'],
      },
    ],
  },
  {
    id: 'technology',
    name: '技术产品',
    hierarchyRole: 'category',
    revenue: 34544000,
    productRevenue: 26944320,
    serviceRevenue: 7599680,
    orders: 6990,
    onlineOrders: 4404,
    offlineOrders: 2586,
    avgOrder: 4942,
    completion: 0.991,
    adjustmentFactor: 0.95,
    owner: '程澈',
    status: '待复核',
    verified: false,
    updatedAt: '2026-08-20T16:00:00.000Z',
    children: [
      {
        id: 'technology-mobile',
        name: '移动终端',
        hierarchyRole: 'subcategory',
        revenue: 16560000,
        productRevenue: 12916800,
        serviceRevenue: 3643200,
        orders: 3620,
        onlineOrders: 2281,
        offlineOrders: 1339,
        avgOrder: 4575,
        completion: 0.99675,
        adjustmentFactor: 1.04,
        owner: '程澈',
        status: '已核验',
        verified: true,
        updatedAt: '2026-08-20T16:00:00.000Z',
        children: [
          {
            id: 'mobile-east',
            name: '华东',
            hierarchyRole: 'region',
            revenue: 8786000,
            productRevenue: 6853080,
            serviceRevenue: 1932920,
            orders: 1880,
            onlineOrders: 1184,
            offlineOrders: 696,
            avgOrder: 4673,
            completion: 1.0115,
            adjustmentFactor: 1,
            owner: '周宁',
            status: '已核验',
            verified: true,
            updatedAt: '2026-08-20T16:00:00.000Z',
            children: [
              {
                id: 'mobile-shanghai',
                name: '上海',
                hierarchyRole: 'detail',
                revenue: 4862000,
                productRevenue: 3792360,
                serviceRevenue: 1069640,
                orders: 1034,
                onlineOrders: 651,
                offlineOrders: 383,
                avgOrder: 4702,
                completion: 1.036,
                owner: '杨晨',
                status: '已核验',
                verified: true,
                updatedAt: '2026-08-20T16:00:00.000Z',
                adjustmentFactor: 0.91,
              },
              {
                id: 'mobile-zhejiang',
                name: '浙江',
                hierarchyRole: 'detail',
                revenue: 3924000,
                productRevenue: 3060720,
                serviceRevenue: 863280,
                orders: 846,
                onlineOrders: 533,
                offlineOrders: 313,
                avgOrder: 4638,
                completion: 0.987,
                owner: '吴哲',
                status: '已核验',
                verified: true,
                updatedAt: '2026-08-20T16:00:00.000Z',
                adjustmentFactor: 0.89,
              },
            ],
          },
          {
            id: 'mobile-north',
            name: '华北',
            hierarchyRole: 'region',
            revenue: 7774000,
            productRevenue: 6063720,
            serviceRevenue: 1710280,
            orders: 1740,
            onlineOrders: 1096,
            offlineOrders: 644,
            avgOrder: 4468,
            completion: 0.982,
            adjustmentFactor: 0.84,
            owner: '赵敏',
            status: '已核验',
            verified: true,
            updatedAt: '2026-08-20T16:00:00.000Z',
            children: [
              {
                id: 'mobile-beijing',
                name: '北京',
                hierarchyRole: 'detail',
                revenue: 5126000,
                productRevenue: 3998280,
                serviceRevenue: 1127720,
                orders: 1120,
                onlineOrders: 706,
                offlineOrders: 414,
                avgOrder: 4577,
                completion: 1.018,
                owner: '孙毅',
                status: '待复核',
                verified: false,
                updatedAt: '2026-08-20T16:00:00.000Z',
                adjustmentFactor: 0.84,
              },
              {
                id: 'mobile-tianjin',
                name: '天津',
                hierarchyRole: 'detail',
                revenue: 2648000,
                productRevenue: 2065440,
                serviceRevenue: 582560,
                orders: 620,
                onlineOrders: 391,
                offlineOrders: 229,
                avgOrder: 4271,
                completion: 0.946,
                owner: '徐昕',
                status: '已核验',
                verified: true,
                updatedAt: '2026-08-19T16:00:00.000Z',
                adjustmentFactor: 0.8,
              },
            ],
          },
        ],
      },
      {
        id: 'technology-equipment',
        name: '办公设备',
        hierarchyRole: 'subcategory',
        revenue: 17984000,
        productRevenue: 14027520,
        serviceRevenue: 3956480,
        orders: 3370,
        onlineOrders: 2123,
        offlineOrders: 1247,
        avgOrder: 5336,
        completion: 0.98525,
        adjustmentFactor: 1.02,
        owner: '程澈',
        status: '待复核',
        verified: false,
        updatedAt: '2026-08-20T16:00:00.000Z',
        children: [
          {
            id: 'equipment-south',
            name: '华南',
            hierarchyRole: 'region',
            revenue: 11214000,
            productRevenue: 8746920,
            serviceRevenue: 2467080,
            orders: 1960,
            onlineOrders: 1235,
            offlineOrders: 725,
            avgOrder: 5721,
            completion: 1.023,
            adjustmentFactor: 0.87,
            owner: '苏然',
            status: '已核验',
            verified: true,
            updatedAt: '2026-08-20T16:00:00.000Z',
            children: [
              {
                id: 'equipment-shenzhen',
                name: '深圳',
                hierarchyRole: 'detail',
                revenue: 6286000,
                productRevenue: 4903080,
                serviceRevenue: 1382920,
                orders: 1050,
                onlineOrders: 662,
                offlineOrders: 388,
                avgOrder: 5987,
                completion: 1.052,
                owner: '黄清',
                status: '已核验',
                verified: true,
                updatedAt: '2026-08-20T16:00:00.000Z',
                adjustmentFactor: 1.07,
              },
              {
                id: 'equipment-guangzhou',
                name: '广州',
                hierarchyRole: 'detail',
                revenue: 4928000,
                productRevenue: 3843840,
                serviceRevenue: 1084160,
                orders: 910,
                onlineOrders: 573,
                offlineOrders: 337,
                avgOrder: 5415,
                completion: 0.994,
                owner: '罗蔚',
                status: '待复核',
                verified: false,
                updatedAt: '2026-08-20T16:00:00.000Z',
                adjustmentFactor: 0.91,
              },
            ],
          },
          {
            id: 'equipment-central',
            name: '华中',
            hierarchyRole: 'region',
            revenue: 6770000,
            productRevenue: 5280600,
            serviceRevenue: 1489400,
            orders: 1410,
            onlineOrders: 888,
            offlineOrders: 522,
            avgOrder: 4801,
            completion: 0.9475,
            adjustmentFactor: 0.95,
            owner: '赵敏',
            status: '已核验',
            verified: true,
            updatedAt: '2026-08-20T16:00:00.000Z',
            children: [
              {
                id: 'equipment-wuhan',
                name: '武汉',
                hierarchyRole: 'detail',
                revenue: 3824000,
                productRevenue: 2982720,
                serviceRevenue: 841280,
                orders: 770,
                onlineOrders: 485,
                offlineOrders: 285,
                avgOrder: 4966,
                completion: 0.968,
                owner: '韩睿',
                status: '已核验',
                verified: true,
                updatedAt: '2026-08-19T16:00:00.000Z',
                adjustmentFactor: 1.06,
              },
              {
                id: 'equipment-zhengzhou',
                name: '郑州',
                hierarchyRole: 'detail',
                revenue: 2946000,
                productRevenue: 2297880,
                serviceRevenue: 648120,
                orders: 640,
                onlineOrders: 403,
                offlineOrders: 237,
                avgOrder: 4603,
                completion: 0.927,
                owner: '陈叶',
                status: '异常',
                verified: false,
                updatedAt: '2026-08-19T16:00:00.000Z',
                adjustmentFactor: 1,
              },
            ],
          },
        ],
      },
    ],
    regionSummaries: [
      {
        id: 'technology-summary-east',
        name: '华东',
        hierarchyRole: 'region',
        revenue: 8786000,
        productRevenue: 6853080,
        serviceRevenue: 1932920,
        orders: 1880,
        onlineOrders: 1184,
        offlineOrders: 696,
        avgOrder: 4673,
        completion: 1.0141156385158205,
        owner: '程澈',
        status: '已核验',
        verified: true,
        updatedAt: '2026-08-20T16:00:00.000Z',
        adjustmentFactor: 0.9,
        detailIds: ['mobile-shanghai', 'mobile-zhejiang'],
      },
      {
        id: 'technology-summary-north',
        name: '华北',
        hierarchyRole: 'region',
        revenue: 7774000,
        productRevenue: 6063720,
        serviceRevenue: 1710280,
        orders: 1740,
        onlineOrders: 1097,
        offlineOrders: 643,
        avgOrder: 4468,
        completion: 0.9934751736557756,
        owner: '程澈',
        status: '待复核',
        verified: false,
        updatedAt: '2026-08-20T16:00:00.000Z',
        adjustmentFactor: 0.82,
        detailIds: ['mobile-beijing', 'mobile-tianjin'],
      },
      {
        id: 'technology-summary-south',
        name: '华南',
        hierarchyRole: 'region',
        revenue: 11214000,
        productRevenue: 8746920,
        serviceRevenue: 2467080,
        orders: 1960,
        onlineOrders: 1235,
        offlineOrders: 725,
        avgOrder: 5721,
        completion: 1.0265118601747816,
        owner: '程澈',
        status: '待复核',
        verified: false,
        updatedAt: '2026-08-20T16:00:00.000Z',
        adjustmentFactor: 0.99,
        detailIds: ['equipment-shenzhen', 'equipment-guangzhou'],
      },
      {
        id: 'technology-summary-central',
        name: '华中',
        hierarchyRole: 'region',
        revenue: 6770000,
        productRevenue: 5280600,
        serviceRevenue: 1489400,
        orders: 1410,
        onlineOrders: 888,
        offlineOrders: 522,
        avgOrder: 4801,
        completion: 0.9501586410635156,
        owner: '程澈',
        status: '异常',
        verified: false,
        updatedAt: '2026-08-19T16:00:00.000Z',
        adjustmentFactor: 1.03,
        detailIds: ['equipment-wuhan', 'equipment-zhengzhou'],
      },
    ],
  },
];
